webapp/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import InputRequired, Length
from flask_babel import lazy_gettext as _l

class CommentForm(FlaskForm):
    name = StringField(
        _l('Name'), [InputRequired(), Length(max=255)]
    )
    text = TextAreaField(_l('Comment'), [InputRequired()])

class PostForm(FlaskForm):
    title = StringField(
        _l('Title'),
        [InputRequired(), Length(max=255)]
    )
    text = TextAreaField(_l('Content'), [InputRequired()])

webapp/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap4
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from sqlalchemy import MetaData
from flask_debugtoolbar import DebugToolbarExtension
from dotenv import load_dotenv
from flask_caching import Cache
from flask_moment import Moment

convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=convention), )
migrate = Migrate()
debug_toolbar = DebugToolbarExtension()
cache = Cache()
moment = Moment()

def create_app(object_name):
    """
    Create and configure a Flask application.

    This function initializes and configures a Flask application with various
    extensions and modules. It sets up routes and configurations based on the
    provided `object_name`.

    Args:
        object_name (str): The name of the configuration object to use.

    Returns:
        Flask: The configured Flask application instance.

    Example usage:
    app = create_app('config.DevelopmentConfig')
    """
    load_dotenv()
    app = Flask(__name__)
    app.config.from_object(object_name)
    bootstrap = Bootstrap4(app)
    cache.init_app(app)

    db.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)
    debug_toolbar.init_app(app)
    moment.init_app(app)


    from .auth import create_module as auth_create_module
    from .blog import create_module as blog_create_module
    from .main import create_module as main_create_module
    from .api import create_module as api_create_module
    from .admin import create_module as admin_create_module
    from .babel import create_module as babel_create_module

    auth_create_module(app)
    blog_create_module(app)
    main_create_module(app)
    api_create_module(app)
    admin_create_module(app)
    babel_create_module(app)
    return app

webapp/admin/__init__.py
from flask_admin import Admin
from .. import db
from .controllers import CustomModelView, CustomView
from webapp.blog.models import Post, Comment, Tag
from webapp.auth.models import User, Role
import os.path as op

admin = Admin()

def create_module(app, **kwargs):
    admin.init_app(app)
    admin.add_view(CustomView(name='Custom'))

    models = [User, Role, Comment, Tag, Post]


    for model in models:
        admin.add_view(CustomModelView(model, db.session, category='Models'))
    

webapp/admin/controllers.py
from flask_admin import BaseView, expose
from flask_admin.contrib.sqla import ModelView
from flask_admin.contrib.fileadmin import FileAdmin
from flask_login import login_required, current_user

from webapp.auth import has_role

class CustomView(BaseView):
    @expose('/')
    @login_required
    @has_role('admin')
    def index(self):
        return self.render('admin/custom.html')
    
    @expose('/second_page')
    @login_required
    @has_role('admin')
    def second_page(self):
        return self.render('admin/second_page.html')
    
class CustomModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.has_role('admin')

webapp/api/__init__.py
from flask_restful import Api
from .blog.controllers import PostApi, CommentApi

rest_api = Api()

def create_module(app, **kwargs):

    rest_api.add_resource(
        PostApi,
        '/api/post',
        '/api/post/<int:post_id>'
    )
    rest_api.add_resource(
        CommentApi,
        '/api/comment',
        '/api/comment/<int:comment_id>',
        '/api/post/<int:post_id>/comments',
    )
    rest_api.init_app(app)

webapp/babel/__init__.py
from flask import has_request_context, session
from flask_babel import Babel

babel = Babel()


def get_locale():
    """
    Get the user's preferred locale based on the session.

    Returns:
    - str: The user's preferred locale (e.g., 'en' for English).
    """
    if has_request_context():
        locale = session.get('locale')
        if locale:
            return locale
        session['locale'] = 'en'
        return session['locale']

def create_module(app, **kwargs):
    """
    Initialize the Babel extension and register the Babel blueprint with the Flask app.

    Args:
    - app (Flask): The Flask application.
    - **kwargs: Additional keyword arguments (if any).

    Returns:
    - None
    """
    babel.init_app(app, locale_selector=get_locale)
    from .controllers import babel_blueprint
    app.register_blueprint(babel_blueprint)

webapp/babel/controllers.py
from flask import Blueprint, session, redirect, url_for

babel_blueprint = Blueprint(
    'babel',
    __name__,
    url_prefix="/babel"
)

@babel_blueprint.route('/<string:locale>')
def index(locale):
    """
    Change the user's preferred locale and redirect to the home page.

    Args:
    - locale (str): The user's selected locale.

    Returns:
    - Redirects to the 'blog.home' route after updating the session's 'locale' variable.
    """
    session['locale'] = locale
    return redirect(url_for('blog.home'))

webapp/blog/__init__.py
def create_module(app, **kwargs):
    """
    Register the Blog Blueprint with the Flask application.

    Args:
    - app (Flask): The Flask application.
    - **kwargs: Additional keyword arguments (if any).

    Returns:
    - None
    """
    from .controllers import blog_blueprint
    app.register_blueprint(blog_blueprint)

webapp/blog/controllers.py
import datetime
from flask import (render_template,
                    Blueprint, 
                    flash, 
                    redirect, 
                    url_for, 
                    current_app, 
                    abort, 
                    request, 
                    get_flashed_messages, 
                    session,
                    g)
from flask_login import login_required, current_user
from .models import db, Post, Tag, Comment

from .forms import CommentForm, PostForm
from ..auth.models import User
from ..auth import has_role
from .. import cache
from flask_babel import _, get_locale

blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix='/blog'
)

@blog_blueprint.before_request
def before_request():
    """
    Execute actions before handling a request.

    This function sets the locale for the request.

    Returns:
    - None
    """
    g.locale = str(get_locale())

def make_cache_key(*args, **kwargs):
    """
    Generate a cache key for the current request.

    This function creates a unique cache key based on request path, query parameters, user roles, locale, and flashed messages.

    Args:
    - *args: Positional arguments.
    - **kwargs: Keyword arguments.

    Returns:
    - bytes: A cache key encoded in UTF-8.
    """
    path = request.path
    args = str(hash(frozenset(request.args.items())))
    messages = str(hash(frozenset(get_flashed_messages())))
    if current_user.is_authenticated:
        roles = str(current_user.roles)
    else:
        roles=""
    return (path + args + roles + session.get('locale', '') + messages).encode('utf-8')

@cache.cached(timeout=7200, key_prefix="sidebar_data")
def sidebar_data():
    """
    Retrieve data for the sidebar, including recent posts and top tags.

    Returns:
    - Tuple: A tuple containing recent posts and top tags.
    """
    recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
    # Using a joined load to get the posts with their associated tags
    posts_with_tags = Post.query.options(db.joinedload(Post.tags)).all()

    # Counting the occurrences of each tag
    tag_count = {}
    for post in posts_with_tags:
        for tag in post.tags:
            tag_count[tag] = tag_count.get(tag, 0) + 1

    # Getting the top tags based on the count
    top_tags = sorted(tag_count.items(), key=lambda x: x[1], reverse=True)[:5]
    return recent, top_tags

@blog_blueprint.route('/')
@blog_blueprint.route('/home')
@cache.cached(timeout=60)
def home():
    """
    Display the home page with a list of recent posts and top tags.

    Returns:
    - Flask response: Rendered home page template.
    """
    page = request.args.get('page',1, type=int)
    posts = Post.query.order_by(Post.publish_date.desc()).paginate(page=page,per_page=current_app.config.get('POSTS_PER_PAGE', 10),error_out=False)

    recent, top_tags = sidebar_data()

    return render_template('home.html', posts=posts, recent=recent, top_tags=top_tags)

@blog_blueprint.route('/followed_posts')
@login_required
@cache.cached(timeout=60)
def followed_posts():
    """
    Display posts of users followed by the current user.

    Returns:
    - Flask response: Rendered home page template.
    """
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(page=page,per_page=current_app.config.get('POSTS_PER_PAGE', 10),error_out=False)

    recent, top_tags = sidebar_data()

    return render_template('home.html', posts=posts, recent=recent, top_tags=top_tags)

@blog_blueprint.route('/new_post', methods=['GET', 'POST'])
@login_required
@has_role('poster')
def new_post():
    """
    Allow users to create a new post.

    Returns:
    - Flask response: Rendered new post creation form or redirects to the created post.
    """
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post()
        new_post.title = form.title.data
        new_post.user_id = current_user.id
        new_post.text = form.text.data
        new_post.publish_date = datetime.datetime.utcnow()
        db.session.add(new_post)
        db.session.commit()
        flash(_('Post added'), category='success')
        return redirect(url_for('.post', post_id=new_post.id))
    return render_template('new.html', form=form)

@blog_blueprint.route('/edit/<int:id>', methods=['GET','POST'])
@login_required
def edit_post(id):
    """
    Allow users to edit an existing post.

    Args:
    - id (int): The ID of the post to edit.

    Returns:
    - Flask response: Rendered post editing form or redirects to the edited post.
    """
    post = Post.query.get_or_404(id)
    #Current user can edit posts
    if current_user.id == post.user.id:
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.text = form.text.data
            post.publish_date = datetime.datetime.utcnow()
            db.session.merge(post)
            db.session.commit()
            return redirect(url_for('.post', post_id=post.id))
        form.title.data = post.title
        form.text.data = post.text
        return render_template('edit.html', form=form, post=post)
    abort(403)

@blog_blueprint.route('/post/<int:post_id>', methods=['GET', 'POST'])
@cache.cached(timeout=60, key_prefix=make_cache_key)
def post(post_id):
    """
    Display a specific post, including comments.

    Args:
    - post_id (int): The ID of the post to display.

    Returns:
    - Flask response: Rendered post page with comments.
    """
    form = CommentForm()
    can_comment = current_user.is_authenticated

    if form.validate_on_submit() and can_comment:
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        new_comment.date = datetime.datetime.utcnow()
        try:
            db.session.add(new_comment)
            db.session.commit()
        except Exception as e:
            flash('Error adding your comment: %s' % str(e), category='error')
            db.session.rollback()
        else:
            flash(_('Comment added'), category='info')
        return redirect(url_for('blog.post', post_id=post_id))
    else:
        flash(_('Login to comment'), category='info')
    
    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'post.html',
        post=post,
        tags=tags,
        comments=comments,
        recent=recent,
        top_tags=top_tags,
        form=form,
    )

@blog_blueprint.route('/tag/<string:tag_name>')
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_tag(tag_name):
    """
    Display posts associated with a specific tag.

    Args:
    - tag_name (str): The name of the tag to filter posts.

    Returns:
    - Flask response: Rendered tag-specific posts page.
    """
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'tag.html',
        tag=tag,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )

@blog_blueprint.route('/user/<string:username>')
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_user(username):
    """
    Display posts created by a specific user.

    Args:
    - username (str): The username of the user to filter posts.

    Returns:
    - Flask response: Rendered user-specific posts page.
    """
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'user.html',
        user=user,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )

webapp/main/__init__.py
def create_module(app, **kwargs):
    """
    Register the 'main_blueprint' in the Flask application.

    This function registers the 'main_blueprint' with the provided Flask
    application, allowing it to handle routes and views for the main section
    of the application.

    Parameters:
    - app (Flask app): The Flask application to register the blueprint with.
    - **kwargs: Additional keyword arguments (if any) that can be passed.

    Returns:
    None
    """
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template

main_blueprint = Blueprint('main', __name__, template_folder='../templates/main')

@main_blueprint.route('/')
def index():
    """
    Redirect to the 'blog.home' route.

    This route function redirects the user to the 'blog.home' route, which is
    typically the main landing page of the application.

    Returns:
    - Redirects the user to the 'blog.home' route.
    """
    return redirect(url_for('blog.home'))

webapp/templates/blog/edit.html
{% extends 'base.html' %}
{% block title %}Post Creation{% endblock %}
{% block body %}
    <div class="p-4 shadow-sm">
        <div class="row">
            <div class="col">
                <h1>Edit Post</h1>
            </div>
        </div>
        <div class="row">
            <form method="POST" action="{{ url_for('.edit_post', id=post.id) }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title.label }}
                    {% if form.title.errors %}
                    {% for e in form.title.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.title(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.errors %}
                    {% for e in form.text.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.text(id='editor', class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
<script 
      src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
</script>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
{% endblock %}

webapp/templates/blog/home.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}Home{% endblock %}
{% block leftbody %}

{{ macros.render_posts(posts) }}
{{ macros.render_pagination(posts, 'blog.home') }}
{% endblock %}

webapp/templates/blog/new.html
{% extends 'base.html' %}
{% block title %}Post Creations{% endblock %}
{% block body %}
    <div class="p-4 shadow-sm">
        <div class="row">
            <div class="col">
                <h1>Create a New Post</h1>
            </div>
        </div>
        <div class="row">
            <form method="POST" action="{{ url_for('.new_post') }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title.label }}
                    {% if form.title.errors %}
                    {% for e in form.title.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.title(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.errors %}
                    {% for e in form.text.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.text(id='editor', class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Submit" >
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
<script 
      src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
</script>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
{% endblock %}

webapp/templates/blog/post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block leftbody %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>{{ post.title }}</h1>
        </div>
    </div>
    <div class="row shadow-sm">
        <div class="col-lg-6">
            <p>Written By <a href="{{ url_for('blog.posts_by_user', username=post.user.username) }}">{{ post.user.username }}</a> on {{ moment(post.publish_date).format('LLL') }}</p>
        </div>
        <div class="col-lg-6">
            <p class="text-right"> Tags: {% for tag in tags %}
                <a href="{{ url_for('blog.posts_by_tag', tag_name=tag.title) }}">{{ tag.title }}</a>
                {% endfor %}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ post.text | safe }}
        </div>
    </div>
    {% if current_user.id == post.user_id %}
    <div class="col-lg-2">
        <a href="{{ url_for('.edit_post', id=post.id) }}" class="btn
        btn-primary">Edit</a>
    </div>
    {% endif %}
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>New Comment</h4>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.name.label }}
                    {% if form.name.errors %}
                        {% for e in form.name.errors %}
                            <p class="form-text text-muted">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.name(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.label %}
                        {% for e in form.text.errors %}
                            <p class="form-text text-muted">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.text(class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Add Comment"></input>
            </form>
        </div>
    </div>
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            {% if comments | length == 0 %}
            <p>There are no comments for this post</p>
            {% else %}
            {% for comment in comments %}
            <div class="shadow-sm p-2">
                <img src="{{ comment.avatar(70) }}">
                <dt>Comment by: {{ comment.name }}, {{ moment(comment.date).fromNow() }}</dt>
                <dd>{{ comment.text }}</dd>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/blog/rightbody.html
<div class='row'>
    <div class='col'>
        <h5>{{_('Recent Posts')}}</h5>
    </div>
</div>
<ul class="list-group">
    {% for post in recent %}
    <li class="list-group-item">
        <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>
<div class="row">
    <div class="col">
        <h5>{{_('Popular Tags')}}</h5>
    </div>
</div>
<ul class="list-group">
    {% for tag in top_tags %}
    <li class="list-group-item">
        <a href="{{ url_for('blog.posts_by_tag', tag_name=tag[0].title) }}">{{ tag[0].title }}</a>
    </li>
    {% endfor %}
</ul>

webapp/templates/blog/tag.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ tag.title }}{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts With Tag {{ tag.title }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}
{% endblock %}

webapp/templates/blog/user.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}{{ user.username }}'s Posts{% endblock %}
<hr>
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts By {{ user.username }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}
{% endblock %}