webapp/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import InputRequired, Length
from flask_babel import lazy_gettext as _l

class CommentForm(FlaskForm):
    name = StringField(
        _l('Name'), [InputRequired(), Length(max=255)]
    )
    text = TextAreaField(_l('Comment'), [InputRequired()])

class PostForm(FlaskForm):
    title = StringField(
        _l('Title'),
        [InputRequired(), Length(max=255)]
    )
    text = TextAreaField(_l('Content'), [InputRequired()])

webapp/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap4
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from sqlalchemy import MetaData
from flask_debugtoolbar import DebugToolbarExtension
from dotenv import load_dotenv
from flask_caching import Cache
from flask_moment import Moment

convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=convention), )
migrate = Migrate()
debug_toolbar = DebugToolbarExtension()
cache = Cache()
moment = Moment()

def create_app(object_name):
    """
    Create and configure a Flask application.

    This function initializes and configures a Flask application with various
    extensions and modules. It sets up routes and configurations based on the
    provided `object_name`.

    Args:
        object_name (str): The name of the configuration object to use.

    Returns:
        Flask: The configured Flask application instance.

    Example usage:
    app = create_app('config.DevelopmentConfig')
    """
    load_dotenv()
    app = Flask(__name__)
    app.config.from_object(object_name)
    bootstrap = Bootstrap4(app)
    cache.init_app(app)

    db.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)
    debug_toolbar.init_app(app)
    moment.init_app(app)


    from .auth import create_module as auth_create_module
    from .blog import create_module as blog_create_module
    from .main import create_module as main_create_module
    from .api import create_module as api_create_module
    from .admin import create_module as admin_create_module
    from .babel import create_module as babel_create_module

    auth_create_module(app)
    blog_create_module(app)
    main_create_module(app)
    api_create_module(app)
    admin_create_module(app)
    babel_create_module(app)
    return app

webapp/admin/__init__.py
from flask_admin import Admin
from .. import db
from .controllers import CustomModelView, CustomView
from webapp.blog.models import Post, Comment, Tag
from webapp.auth.models import User, Role
import os.path as op

admin = Admin()

def create_module(app, **kwargs):
    admin.init_app(app)
    admin.add_view(CustomView(name='Custom'))

    models = [User, Role, Comment, Tag, Post]


    for model in models:
        admin.add_view(CustomModelView(model, db.session, category='Models'))
    

webapp/admin/controllers.py
from flask_admin import BaseView, expose
from flask_admin.contrib.sqla import ModelView
from flask_admin.contrib.fileadmin import FileAdmin
from flask_login import login_required, current_user

from webapp.auth import has_role

class CustomView(BaseView):
    @expose('/')
    @login_required
    @has_role('admin')
    def index(self):
        return self.render('admin/custom.html')
    
    @expose('/second_page')
    @login_required
    @has_role('admin')
    def second_page(self):
        return self.render('admin/second_page.html')
    
class CustomModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.has_role('admin')

webapp/api/__init__.py
from flask_restful import Api
from .blog.controllers import PostApi, CommentApi

rest_api = Api()

def create_module(app, **kwargs):

    rest_api.add_resource(
        PostApi,
        '/api/post',
        '/api/post/<int:post_id>'
    )
    rest_api.add_resource(
        CommentApi,
        '/api/comment',
        '/api/comment/<int:comment_id>',
        '/api/post/<int:post_id>/comments',
    )
    rest_api.init_app(app)

webapp/api/blog/controllers.py
import datetime
from email.policy import strict

from flask import abort, current_app, jsonify, request
from flask_restful import Resource, fields, marshal_with, abort
from flask_jwt_extended import jwt_required, get_jwt_identity
from webapp.blog.models import db, Post, Tag, Comment
from webapp.auth.models import User
from .parsers import (
    post_get_parser,
    post_post_parser,
    post_put_parser,
    comment_get_parser,
    comment_post_parser,
    comment_put_parser
)
from .fields import HTMLField

nested_tag_fields = {
    'id': fields.Integer(),
    'title': fields.String(),
}

post_fields = {
    'id': fields.Integer(),
    'user_id': fields.Integer(),
    'title': fields.String(),
    'text': HTMLField(),
    'tags': fields.List(fields.Nested(nested_tag_fields)),
    'publish_date': fields.DateTime(dt_format='iso8601')
}
comment_fields = {
    'id': fields.Integer(),
    'post_id': fields.Integer(),
    'user_id': fields.Integer(),
    'name': fields.String(),
    'text': HTMLField(),
    'date': fields.DateTime(dt_format='iso8601')
}
def add_tags_to_post(post, tags_list):
    for item in tags_list:
        tag = Tag.query.filter_by(title=item).first()

        if tag:
            post.tags.append(tag)
        else:
            new_tag = Tag(item)
            post.tags.append(new_tag)

class PostApi(Resource):
    @marshal_with(post_fields)
    @jwt_required()
    def get(self, post_id=None):
        """
        Get a post by its ID or a list of posts.

        Args:
            post_id (int): The ID of the post to retrieve. Defaults to None.

        Returns:
            Post or list of Post: The requested post(s).

        Raises:
            404: If the post with the given ID is non-existent.

        400: If 'page' or 'user' args are invalid.

        401: If authentication is required.

        403: If trying to edit a post not created by the current user.
        """
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404, message="Post id is non-existent")
            return post
        else:
            args = post_get_parser.parse_args()
            page = args['page'] or 1

            if args['user']:
                user = User.query.filter_by(username=args['user']).first()
                if not user:
                    abort(404, message="Username not found...")
                
                posts = user.posts.order_by(
                    Post.publish_date.desc()
                ).paginate(page=args['page'] or 1,per_page=current_app.config.get('POSTS_PER_PAGE', 10),error_out=False)
            else:
                posts = Post.query.order_by(
                    Post.publish_date.desc()
                ).paginate(page=args['page'] or 1,per_page=current_app.config.get('POSTS_PER_PAGE', 10),error_out=False)

            return posts.items
    
    @jwt_required()
    def post(self):
        """
        Create a new post.

        Returns:
            dict: A dictionary containing the ID of the newly created post.

        Raises:
            400: If the request is missing required arguments.

            401: If authentication is required.
        """
        args = post_post_parser.parse_args(strict=True)
        new_post = Post(args['title'])
        new_post.user_id = get_jwt_identity()
        new_post.text = args['text']
        new_post.publish_date = datetime.datetime.now()

        if args['tags']:
            add_tags_to_post(new_post, args['tags'])

        db.session.add(new_post)
        db.session.commit()
        return {'id': new_post.id}, 201
    
    @jwt_required()
    def put(self, post_id=None):
        """
        Update an existing post.

        Args:
            post_id (int): The ID of the post to update. Defaults to None.

        Returns:
            dict: A dictionary containing the ID of the updated post.

        Raises:
            400: If the 'post_id' is not provided.

            401: If authentication is required.

            403: If trying to edit a post not created by the current user.
        """
        if not post_id:
            abort(400, message="Post id required...")
        post = Post.query.get(post_id)
        if not post:
            abort(404, message="Post non-existent...")
        args = post_put_parser.parse_args(strict=True)
        if get_jwt_identity() != post.user_id:
            abort(403,message="Can't edit post you didn't create")
        if args['title']:
            post.title = args['title']
        if args['text']:
            post.text = args['text']
        if args['tags']:
            add_tags_to_post(post, args['tags'])

        db.session.merge(post)
        db.session.commit()
        return {'id': post.id}, 201
    
    @jwt_required()
    def delete(self, post_id=None):
        """
        Delete an existing post.

        Args:
            post_id (int): The ID of the post to delete. Defaults to None.

        Returns:
            str: An empty string.

        Raises:
            400: If the 'post_id' is not provided.

            401: If authentication is required.

            404: If the post with the given ID is non-existent.

            403: If trying to delete a post not created by the current user.
        """
        if not post_id:
            abort(400, message="Post id required...")
        post = Post.query.get(post_id)
        if not post:
            abort(404, message="Post non-existent...")
        if get_jwt_identity() != post.user_id:
            abort(401, message="Authentication required...")

        db.session.delete(post)
        db.session.commit()
        return "", 204
    
class CommentApi(Resource):
    @marshal_with(comment_fields)
    @jwt_required()
    def get(self, comment_id=None, post_id=None):
        """
        Get a comment by its ID, a list of comments, or comments for a specific post or user.

        Args:
            comment_id (int): The ID of the comment to retrieve. Defaults to None.
            post_id (int): The ID of the post to retrieve comments for. Defaults to None.

        Returns:
            Comment or list of Comment: The requested comment(s).

        Raises:
            400: If 'page' or 'user' args are invalid.

            401: If authentication is required.

            403: If trying to edit a comment not created by the current user.
        """
        if comment_id:
            comment = Comment.query.get(comment_id)
            if not comment:
                abort(404, message="Comment id non-exixtent")
                print(f"comment: {comment}")
            return comment
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404, message='Post not found ...')
            comments = post.comments.order_by(
                Comment.date.desc()
            )
            return comments
            
        else:
            args = comment_get_parser.parse_args()
            page = args['page'] or 1

            if args['user']:
                user = User.query.filter_by(username=args['user']).first()

                if not user:
                    abort(404, message='User not found...')
                comments = user.comments.order_by(
                    Comment.date.desc()
                ).paginate(page=args['page'] or 1, per_page=10, error_out=False)
            else:
                comments = Comment.query.order_by(
                    Comment.date.desc()
                ).paginate(page=args['page'] or 1, per_page=10, error_out=False)
            return comments.items
    
    @jwt_required()
    def post(self, post_id=None):
        """
        Create a new comment for a specific post.

        Args:
            post_id (int): The ID of the post to add a comment to. Defaults to None.

        Returns:
            dict: A dictionary containing the ID of the newly created comment.

        Raises:
            400: If the 'post_id' is not provided or if the request is missing required arguments.

            401: If authentication is required.
        """
        if not post_id:
            abort(400, message="Post id required...")
        post = Post.query.get(post_id)
        if not post:
            abort(404, message="Post non-existent...")
        args = comment_post_parser.parse_args(strict=True)
        new_comment = Comment()
        new_comment.text = args['text']
        new_comment.name = args['name']
        new_comment.user_id = get_jwt_identity()
        new_comment.post_id = post.id
        new_comment.date = datetime.datetime.now()

        db.session.add(new_comment)
        db.session.commit()
        return {'id': new_comment.id}, 201

    @jwt_required()
    def put(self, comment_id=None):
        """
        Update an existing comment.

        Args:
            comment_id (int): The ID of the comment to update. Defaults to None.

        Returns:
            dict: A dictionary containing the ID of the updated comment.

        Raises:
            400: If the 'comment_id' is not provided.

            401: If authentication is required.

            403: If trying to edit a comment not created by the current user.
        """
        if not comment_id:
            abort(400, message="Comment id required...")
        comment = Comment.query.get(comment_id)
        if not comment:
            abort(404, message="Comment non-existent...")
        args = comment_put_parser.parse_args()
        if get_jwt_identity() != comment.user_id:
            abort(403, message="Can't edit comment you didn't create")
        #if args['name']:
            #comment.name = args['name']
        if args['text']:
            comment.text = args['text']
        
        db.session.merge(comment)
        db.session.commit()
        return {'id': comment.id}, 201
    
    @jwt_required()
    def delete(self, comment_id=None):
        """
        Delete an existing comment.

        Args:

webapp/babel/__init__.py
from flask import has_request_context, session
from flask_babel import Babel

babel = Babel()


def get_locale():
    """
    Get the user's preferred locale based on the session.

    Returns:
    - str: The user's preferred locale (e.g., 'en' for English).
    """
    if has_request_context():
        locale = session.get('locale')
        if locale:
            return locale
        session['locale'] = 'en'
        return session['locale']

def create_module(app, **kwargs):
    """
    Initialize the Babel extension and register the Babel blueprint with the Flask app.

    Args:
    - app (Flask): The Flask application.
    - **kwargs: Additional keyword arguments (if any).

    Returns:
    - None
    """
    babel.init_app(app, locale_selector=get_locale)
    from .controllers import babel_blueprint
    app.register_blueprint(babel_blueprint)

webapp/babel/controllers.py
from flask import Blueprint, session, redirect, url_for

babel_blueprint = Blueprint(
    'babel',
    __name__,
    url_prefix="/babel"
)

@babel_blueprint.route('/<string:locale>')
def index(locale):
    """
    Change the user's preferred locale and redirect to the home page.

    Args:
    - locale (str): The user's selected locale.

    Returns:
    - Redirects to the 'blog.home' route after updating the session's 'locale' variable.
    """
    session['locale'] = locale
    return redirect(url_for('blog.home'))

webapp/blog/__init__.py
def create_module(app, **kwargs):
    """
    Register the Blog Blueprint with the Flask application.

    Args:
    - app (Flask): The Flask application.
    - **kwargs: Additional keyword arguments (if any).

    Returns:
    - None
    """
    from .controllers import blog_blueprint
    app.register_blueprint(blog_blueprint)

webapp/main/__init__.py
def create_module(app, **kwargs):
    """
    Register the 'main_blueprint' in the Flask application.

    This function registers the 'main_blueprint' with the provided Flask
    application, allowing it to handle routes and views for the main section
    of the application.

    Parameters:
    - app (Flask app): The Flask application to register the blueprint with.
    - **kwargs: Additional keyword arguments (if any) that can be passed.

    Returns:
    None
    """
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template

main_blueprint = Blueprint('main', __name__, template_folder='../templates/main')

@main_blueprint.route('/')
def index():
    """
    Redirect to the 'blog.home' route.

    This route function redirects the user to the 'blog.home' route, which is
    typically the main landing page of the application.

    Returns:
    - Redirects the user to the 'blog.home' route.
    """
    return redirect(url_for('blog.home'))

webapp/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">
        {% block styles %}
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css') }}">
            {{ bootstrap.load_css() }}
        {% endblock %}
        <title>{% block title %}Blog{% endblock %}</title>
        {% endblock %}
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container">
            <div class="row">
                <div class="col">
                    {% include 'head.html' %}
                </div>
            </div>
            {% include 'messages.html' %}
            {% block body %}
            <div class="row">
                <div class="col-lg-9">
                    {% block leftbody %}
                    {% endblock %}
                </div>
                <div class="col-lg-3 rounded">
                    {% block rightbody %}
                    {% include 'rightbody.html' %}
                    {% endblock %}
                </div>
            </div>
            {% endblock %}
            {% include 'footer.html' %}
        </div>
        {% block scripts %}
            {{ bootstrap.load_js() }}
            {{ moment.include_moment() }}
            {{ moment.lang(g.locale) }}
            <!-- reCaptcha Integration -->
            <script src='https://www.google.com/recaptcha/api.js' async defer></script>
        {% endblock %}
    </body>
</html>

webapp/templates/footer.html
<hr>
<div class="text-center">Built by Ian Suto.</div>

webapp/templates/head.html
<div class="container bg-info rounded d-flex justify-content-center">
    <div class="align-items-center">
        <!--<i class="fas fa-comments  fa-5x"></i>-->
        <h1><a class="text-white" href="{{ url_for('blog.home') }}">My Blog</a></h1>
        <p>{{ _('Welcome to the Blog!')}}</p>
    </div>
</div>

webapp/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
{% for k,v in kwargs.items() -%}{{ k }}='{{ v }}' {% endfor %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if pagination.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.prev().page) }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}
        {% for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="">{{ page }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item">
                    <a class="page-link">...</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if pagination.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.next().page) }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}

{% macro render_posts(posts, pagination=True) %}
{% if pagination %}
    {% set _posts = posts.items %}
{% else %}
    {% set _posts = posts %}
{% endif %}

{% for post in _posts %}
<div>
    <h1>
        <a class="text-dark" href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
    </h1>
</div>
<div class="row">
    <div class="col">
        {{ post.text | truncate(500) | safe }}
        <a href="{{ url_for('blog.post', post_id=post.id) }}">{{_('Read More')}}</a>
    </div>
</div>
{% endfor %}
{% endmacro %}

webapp/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category,message in messages %}
<div class="alert alert-{{ category }} alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

webapp/templates/navbar.html
{% from 'bootstrap4/nav.html' import render_nav_item %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {{ render_nav_item('blog.home', _('Home')) }}
                
                {% if current_user.is_authenticated and current_user.has_role('poster') %}
                {{ render_nav_item('blog.new_post', _('New Post')) }}
                {% endif %}
                {% if current_user.is_authenticated and current_user.has_role('admin') %}
                {{ render_nav_item('admin.index', _('Admin')) }}
                {% endif %}
                {% if current_user.is_authenticated %}
                {{ render_nav_item('blog.followed_posts', _('Followed Posts')) }}
                {{ render_nav_item('auth.logout', _('Logout')) }}
                {{ render_nav_item('auth.user_profiles', _('User Profiles')) }}
                {{ render_nav_item('auth.edit_profile', _("Edit Profile")) }}
                {% else %}
                {{ render_nav_item('auth.login', _('Login')) }}
                {{ render_nav_item('auth.register', _('Register')) }}
                {% endif %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"
                    id="navbarDropdown" role="button" data-toggle="dropdown">
                    Lang
                    </a>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{url_for('babel.index',
                    locale='en')}}">en</a>
                    <a class="dropdown-item" href="{{url_for('babel.index',
                    locale='pt')}}">pt</a>
                    </div>
                    </li>
                </ul>
            </ul>
        </div>
    </nav>